AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - config.ru
    - db/schema.rb
    - tmp/**/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - config/**/*
